// 30 fact cards from seven documentaries. Each: punchy fact, source, principle, pursuit.
// Sources verified: Inside Job (2010, Ferguson); The One Percent (2006, Jamie Johnson);
// Age of Easy Money (Frontline PBS, 2023, James Jacoby); 97% Owned (2012, Michael Oswald);
// Capital in the Twenty-First Century (Piketty, 2013/2014); Money, Power and Wall Street
// (Frontline PBS, 2012); Born Rich / Generation Wealth (2003, Jamie Johnson).
export const FACT_CARDS = [
  { fact: "For ~40 years after Depression-era reforms, the U.S. had zero financial crises. Deregulation from the 1980s reopened the door.", documentary: "Inside Job", principle: "Guardrails are not the enemy of building — they are what let you build without ruin.", pursuit: "spendwhere" },
  { fact: "The 2008 meltdown cost the world over $20 trillion; not one major executive was criminally prosecuted.", documentary: "Inside Job", principle: "Systems reward those who understand them and punish those who don't. Learn the rules.", pursuit: "retire55" },
  { fact: "Investment banks sold clients securities they were simultaneously betting against.", documentary: "Inside Job", principle: "Know who profits when you lose. Own your own upside.", pursuit: "xrp" },
  { fact: "Ratings agencies were paid by the issuers whose products they rated — AAA on paper that was junk.", documentary: "Inside Job", principle: "Follow the incentive, not the label. Verify before you trust.", pursuit: "mmm" },
  { fact: "The 2004 SEC net-capital change let investment banks lever up to 33:1 — a 3% drop in assets wiped them out.", documentary: "Inside Job", principle: "Leverage magnifies both directions. Build a margin of safety.", pursuit: "realestate" },
  { fact: "In 2004 the top 1% of Americans controlled 42.2% of total financial wealth.", documentary: "The One Percent", principle: "Ownership concentrates. Decide which side of the ledger you're building toward.", pursuit: "retire55" },
  { fact: "Milton Friedman told Jamie Johnson the wealth gap itself is bad — then ended the interview.", documentary: "The One Percent", principle: "Even those who defend the system admit the gap is real. Position accordingly.", pursuit: "linkedin" },
  { fact: "Inherited fortunes routinely dissolve by the third generation without discipline and knowledge.", documentary: "The One Percent", principle: "Capital without stewardship evaporates. Build the habits, not just the balance.", pursuit: "retire55" },
  { fact: "Wealth-preservation advisors form an industry whose only job is keeping money in the same families.", documentary: "The One Percent", principle: "The wealthy systematize preservation. Systematize yours (this app).", pursuit: "spendwhere" },
  { fact: "The Fed's balance sheet grew from ~$1T (2007) to ~$9T (2022) through quantitative easing.", documentary: "Age of Easy Money", principle: "When money is printed, assets inflate. Hold assets, not just dollars.", pursuit: "xrp" },
  { fact: "QE lowered rates to push investors from bonds into stocks — 'it penalizes the saver, favors the debtor.'", documentary: "Age of Easy Money", principle: "In an easy-money world, cash quietly loses. Deploy it.", pursuit: "realestate" },
  { fact: "QE set off the longest bull run in stock-market history — owned mostly by the top 0.1%.", documentary: "Age of Easy Money", principle: "The rally rewards owners. Become one early.", pursuit: "retire55" },
  { fact: "Stiglitz: QE 'increases enormously wealth inequality... it put that on steroids.'", documentary: "Age of Easy Money", principle: "Understand the machine that's redistributing upward, then stand where it flows.", pursuit: "voice" },
  { fact: "The $2.2T CARES Act was the largest stimulus ever; the Fed began buying corporate debt for the first time.", documentary: "Age of Easy Money", principle: "Crises rewrite the rules overnight. Stay liquid and ready.", pursuit: "spendwhere" },
  { fact: "Commercial banks create ~97% of all money — as new debt — the moment they make loans.", documentary: "97% Owned", principle: "Money is created, not found. Learn to originate value, not just chase it.", pursuit: "voice" },
  { fact: "In 1948 notes and coins were 17% of the UK money supply; today under 3% — the rest is digital.", documentary: "97% Owned", principle: "Money is already information. Fintech is the native tongue of the new economy.", pursuit: "spendwhere" },
  { fact: "A mortgage doesn't add to output — it inflates money supply and asset prices.", documentary: "97% Owned", principle: "Distinguish productive credit from speculative credit in your own borrowing.", pursuit: "realestate" },
  { fact: "Where and how much money is created shapes the whole economy — banks decide, not you.", documentary: "97% Owned", principle: "If you don't direct your dollars, someone else's system will. SpendWHERE puts you in the chair.", pursuit: "spendwhere" },
  { fact: "Piketty's law: when return on capital (r) exceeds growth (g), wealth concentrates. Historically r≈4–5%, g≈1.5%.", documentary: "Capital in the Twenty-First Century", principle: "Own assets that compound faster than the economy grows. That's the whole game.", pursuit: "retire55" },
  { fact: "Capital income is far more unequally distributed than labor income.", documentary: "Capital in the Twenty-First Century", principle: "Shift your income mix from labor toward assets. Track the ratio (Dashboard).", pursuit: "xrp" },
  { fact: "In a low-growth society, 'wealth accumulated in the past acquires disproportionate importance.'", documentary: "Capital in the Twenty-First Century", principle: "Start the compounding clock now — time is the largest multiplier.", pursuit: "retire55" },
  { fact: "Large fortunes earn higher returns than small ones — scale itself is an edge.", documentary: "Capital in the Twenty-First Century", principle: "Reinvest to reach the scale where money works harder. Don't consume the seed.", pursuit: "voice" },
  { fact: "Credit default swaps were invented by JP Morgan bankers at a 1994 Boca Raton retreat.", documentary: "Money, Power and Wall Street", principle: "Every giant market began as one small idea. Yours can too.", pursuit: "mmm" },
  { fact: "By 2005 the CDS market was measured in trillions and doubling every year.", documentary: "Money, Power and Wall Street", principle: "Exponential growth is invisible until it isn't. Compound early.", pursuit: "spendwhere" },
  { fact: "Gillian Tett: the innovation 'turned into a Frankenstein monster... spun out of control.'", documentary: "Money, Power and Wall Street", principle: "Build systems you can still control at scale. Design for the downside.", pursuit: "spendwhere" },
  { fact: "AIG was on the hook for $440 billion in credit default swaps when it collapsed.", documentary: "Money, Power and Wall Street", principle: "Never write more risk than you can cover. Size your positions.", pursuit: "xrp" },
  { fact: "'Wall Street got bailed out and Main Street didn't.' (David Wessel)", documentary: "Money, Power and Wall Street", principle: "Don't wait for a rescue. Build your own balance sheet.", pursuit: "retire55" },
  { fact: "Jamie Johnson: 'Inheriting a dollar is not the same as earning one.'", documentary: "Born Rich", principle: "Earned capital carries earned wisdom. Value the building, not just the built.", pursuit: "grades" },
  { fact: "Heirs interviewed in Born Rich were often idle and adrift — money without purpose corrodes.", documentary: "Born Rich", principle: "Wealth is fuel, not destination. Anchor it to purpose (RESPECT/RETURN/RITUAL).", pursuit: "linkedin" },
  { fact: "The ultra-rich treat discussing money as taboo — so heirs learn nothing about managing it.", documentary: "Born Rich / Generation Wealth", principle: "Break the silence. Financial literacy, spoken openly, is itself an inheritance.", pursuit: "grades" }
];
