/**
 * T3.2/T3.3/T3.4 — document generators, and T3.5 — the disclaimer that is
 * stamped on EVERY generated document. Documents are produced for the user
 * to review and file THEMSELVES; SpendWHERE files nothing on their behalf.
 */
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export const LEGAL_DISCLAIMER =
  "DISCLAIMER: This document was generated by SpendWHERE software from information " +
  "you provided. It is not legal advice, SpendWHERE is not a law firm, and no " +
  "attorney-client relationship is created. Review with a licensed attorney before " +
  "use. You are responsible for filing this document yourself and for all fees.";

export interface DocSection {
  heading?: string;
  paragraphs: string[];
}

export interface GeneratedDoc {
  title: string;
  sections: DocSection[];
  /** Full text content — used by tests to assert the disclaimer is present. */
  text: string;
  pdf: Uint8Array;
}

const PAGE = { width: 612, height: 792, margin: 56 }; // US Letter

export async function buildPdf(title: string, sections: DocSection[]): Promise<GeneratedDoc> {
  // T3.5 — the disclaimer is always the final section, on every document.
  const allSections: DocSection[] = [...sections, { heading: "Important notice", paragraphs: [LEGAL_DISCLAIMER] }];

  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.TimesRoman);
  const bold = await doc.embedFont(StandardFonts.TimesRomanBold);

  let page = doc.addPage([PAGE.width, PAGE.height]);
  let y = PAGE.height - PAGE.margin;
  const maxWidth = PAGE.width - PAGE.margin * 2;

  const ensureRoom = (needed: number) => {
    if (y - needed < PAGE.margin) {
      page = doc.addPage([PAGE.width, PAGE.height]);
      y = PAGE.height - PAGE.margin;
    }
  };

  const wrap = (text: string, size: number, f = font): string[] => {
    const words = text.split(" ");
    const lines: string[] = [];
    let line = "";
    for (const word of words) {
      const candidate = line ? `${line} ${word}` : word;
      if (f.widthOfTextAtSize(candidate, size) > maxWidth && line) {
        lines.push(line);
        line = word;
      } else {
        line = candidate;
      }
    }
    if (line) lines.push(line);
    return lines;
  };

  const drawLines = (lines: string[], size: number, f = font, gap = 4) => {
    for (const line of lines) {
      ensureRoom(size + gap);
      page.drawText(line, { x: PAGE.margin, y, size, font: f, color: rgb(0.1, 0.1, 0.1) });
      y -= size + gap;
    }
  };

  drawLines(wrap(title, 18, bold), 18, bold, 8);
  y -= 8;

  for (const section of allSections) {
    if (section.heading) {
      y -= 6;
      drawLines(wrap(section.heading, 13, bold), 13, bold, 6);
    }
    for (const para of section.paragraphs) {
      drawLines(wrap(para, 11), 11);
      y -= 6;
    }
  }

  const text = [title, ...allSections.flatMap((s) => [s.heading ?? "", ...s.paragraphs])].join("\n");
  const pdf = await doc.save({ useObjectStreams: false });
  return { title, sections: allSections, text, pdf };
}

export interface LlcData {
  entityName: string;
  purpose: string;
  duration: string;
  residentAgentName: string;
  registeredOfficeStreet: string;
  registeredOfficeCity: string;
  registeredOfficeZip: string;
  organizerName: string;
  organizerAddress?: string | null;
  management: "member_managed" | "manager_managed";
  memberNames: string[];
  responsiblePartyName?: string | null;
  principalActivity?: string | null;
  expectedEmployees?: number | null;
  businessStartDate?: string | null;
}

/** Fields LARA form CSCL/CD-700 requires before Articles can be generated. */
export const ARTICLES_REQUIRED_FIELDS = [
  "entityName",
  "residentAgentName",
  "registeredOfficeStreet",
  "registeredOfficeCity",
  "registeredOfficeZip",
  "organizerName",
] as const;

export function missingArticlesFields(data: Partial<LlcData>): string[] {
  return ARTICLES_REQUIRED_FIELDS.filter((f) => !data[f]);
}

/** Michigan Articles of Organization (mirrors LARA form CSCL/CD-700). */
export async function articlesOfOrganization(data: LlcData): Promise<GeneratedDoc> {
  return buildPdf("Articles of Organization — Michigan Limited Liability Company", [
    {
      paragraphs: [
        "For use by domestic limited liability companies under the Michigan Limited " +
          "Liability Company Act (Act 23, Public Acts of 1993). This document mirrors " +
          "the fields of LARA form CSCL/CD-700. File online or by mail with the Michigan " +
          "Department of Licensing and Regulatory Affairs, Corporations Division. " +
          "Filing fee: $50.00.",
      ],
    },
    { heading: "Article I — Name", paragraphs: [`The name of the limited liability company is: ${data.entityName}`] },
    { heading: "Article II — Purpose", paragraphs: [data.purpose] },
    {
      heading: "Article III — Duration",
      paragraphs: [
        data.duration === "perpetual"
          ? "The duration of the limited liability company is perpetual."
          : `The duration of the limited liability company is: ${data.duration}`,
      ],
    },
    {
      heading: "Article IV — Resident Agent and Registered Office",
      paragraphs: [
        `1. The name of the resident agent is: ${data.residentAgentName}`,
        `2. The address of the registered office is: ${data.registeredOfficeStreet}, ` +
          `${data.registeredOfficeCity}, Michigan ${data.registeredOfficeZip}`,
      ],
    },
    {
      heading: "Signature of Organizer",
      paragraphs: [
        `Signed this ____ day of ____________, 20___.`,
        `Organizer: ${data.organizerName}${data.organizerAddress ? ` — ${data.organizerAddress}` : ""}`,
        "Signature: ________________________________",
      ],
    },
    {
      heading: "Filing instructions (do this yourself)",
      paragraphs: [
        "1. Search name availability first: https://cofs.lara.state.mi.us/SearchApi/Search/Search",
        "2. File online at https://cofs.lara.state.mi.us/corpweb/loginsystem/login.aspx or mail to: " +
          "Michigan Department of Licensing and Regulatory Affairs, Corporations, Securities & " +
          "Commercial Licensing Bureau, Corporations Division, P.O. Box 30054, Lansing, MI 48909.",
        "3. Pay the $50 filing fee. Expedited review is available for an additional fee.",
        "4. After approval, record your filing date in SpendWHERE so your compliance " +
          "calendar can track the $25 Annual Statement due each February 15.",
      ],
    },
  ]);
}

/** Simple member-managed operating agreement template (T3.3). */
export async function operatingAgreement(data: LlcData): Promise<GeneratedDoc> {
  const members = data.memberNames.length > 0 ? data.memberNames : [data.organizerName];
  return buildPdf(`Operating Agreement of ${data.entityName}`, [
    {
      paragraphs: [
        `This Operating Agreement (the "Agreement") of ${data.entityName}, a Michigan ` +
          `limited liability company (the "Company"), is entered into by and among the ` +
          `Company and the persons executing this Agreement as members (each a "Member").`,
      ],
    },
    {
      heading: "1. Formation",
      paragraphs: [
        "The Company was formed by filing Articles of Organization with the Michigan " +
          "Department of Licensing and Regulatory Affairs under the Michigan Limited " +
          "Liability Company Act.",
      ],
    },
    {
      heading: "2. Members",
      paragraphs: [`The Member(s) of the Company: ${members.join("; ")}.`],
    },
    {
      heading: "3. Management",
      paragraphs: [
        data.management === "member_managed"
          ? "The Company is managed by its Member(s). Each Member has authority to bind the Company in the ordinary course of business."
          : "The Company is managed by one or more Managers designated by the Member(s).",
      ],
    },
    {
      heading: "4. Capital contributions and distributions",
      paragraphs: [
        "Members shall make initial capital contributions as recorded in the Company's " +
          "records. Distributions shall be made to Members in proportion to their " +
          "membership interests at times determined by the Member(s).",
      ],
    },
    {
      heading: "5. Separateness",
      paragraphs: [
        "The Company shall maintain bank accounts, records, and finances separate from " +
          "those of any Member. Members shall not commingle Company funds with personal funds.",
      ],
    },
    {
      heading: "6. Dissolution",
      paragraphs: [
        "The Company may be dissolved by the vote of the Member(s), after which its " +
          "affairs shall be wound up as required by the Act.",
      ],
    },
    {
      heading: "Signatures",
      paragraphs: members.map((m) => `Member: ${m} — Signature: ______________________ Date: ________`),
    },
  ]);
}

/** Resident-agent guidance sheet (T3.3). */
export async function residentAgentGuide(): Promise<GeneratedDoc> {
  return buildPdf("Choosing a Michigan Resident Agent — Guidance", [
    {
      paragraphs: [
        "Every Michigan LLC must continuously maintain a resident agent and a registered " +
          "office in Michigan (MCL 450.4207). The agent accepts legal and state mail for the LLC.",
      ],
    },
    {
      heading: "Your options",
      paragraphs: [
        "1. Yourself — free, but your street address becomes public record and you must be " +
          "available at that Michigan address during business hours.",
        "2. Another Michigan resident you trust — same trade-offs, one step removed.",
        "3. A commercial registered agent service — typically $50–$250/year; keeps your " +
          "home address off the public record and forwards mail.",
      ],
    },
    {
      heading: "Requirements",
      paragraphs: [
        "The agent must be a Michigan resident, or a Michigan corporation/LLC, or a foreign " +
          "entity authorized to do business in Michigan. A P.O. Box alone is not a valid " +
          "registered office address.",
        "LARA mails the pre-filled Annual Statement to the resident agent about 90 days " +
          "before the February 15 due date — so make sure the agent reliably forwards mail.",
      ],
    },
  ]);
}

/** SS-4 (EIN) guided summary (T3.4). Never filed by SpendWHERE. */
export async function ss4Summary(data: LlcData): Promise<GeneratedDoc> {
  return buildPdf(`EIN Application (IRS Form SS-4) — Prepared Answers for ${data.entityName}`, [
    {
      paragraphs: [
        "An EIN is free directly from the IRS. The fastest route is the IRS online " +
          "assistant (issues the EIN immediately if the responsible party has an SSN or " +
          "ITIN): https://www.irs.gov/businesses/small-businesses-self-employed/apply-for-an-employer-identification-number-ein-online",
        "Use the answers below to complete the online interview or paper Form SS-4.",
      ],
    },
    {
      heading: "Your prepared SS-4 answers",
      paragraphs: [
        `Line 1 (Legal name of entity): ${data.entityName}`,
        `Line 7a (Responsible party): ${data.responsiblePartyName ?? "— provide before filing —"}`,
        "Line 7b (SSN/ITIN): you will enter this directly with the IRS — SpendWHERE does not submit it.",
        `Line 9a (Type of entity): Limited Liability Company (LLC)`,
        `Line 10 (Reason for applying): Started new business`,
        `Line 11 (Date business started): ${data.businessStartDate ?? "— provide before filing —"}`,
        `Line 13 (Highest number of employees expected in the next 12 months): ${data.expectedEmployees ?? 0}`,
        `Line 16 (Principal activity): ${data.principalActivity ?? "— provide before filing —"}`,
      ],
    },
    {
      heading: "Third-Party Designee (optional)",
      paragraphs: [
        "The SS-4 Third-Party Designee section lets a service receive your EIN on your " +
          "behalf; the designee's authority ends when the EIN is assigned. You do NOT need " +
          "a paid service — applying yourself online is free and instant.",
      ],
    },
    {
      heading: "After you receive your EIN",
      paragraphs: [
        "Save the IRS confirmation letter (CP 575) in your SpendWHERE Document Vault under " +
          "the 'EIN letter' category. Banks will ask for it when you open a business account.",
      ],
    },
  ]);
}
