import 'dotenv/config';
import fs from 'fs';
import { run, client } from './index.js';
import { seed } from '../seed/seed.js';

let schema = fs.readFileSync(new URL('./schema.sql', import.meta.url), 'utf8');
// schema.sql is written in SQLite dialect, where INTEGER PRIMARY KEY is the
// auto-incrementing rowid. Postgres needs an identity column for the same
// behavior, so translate when DB_CLIENT=pg.
if (client === 'pg') {
  schema = schema.replace(/INTEGER PRIMARY KEY/g, 'INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
}
for (const stmt of schema.split(';').map(s => s.trim()).filter(Boolean)) {
  await run(stmt);
}
await seed();
console.log('The Counting House: schema + seed complete.');
process.exit(0);
